### ISSUE TITLE
new queue on mammouth

### ISSUE THREAD

**Issue by samuelstjean** [SMART-Lab/smartdispatch#102]
Seems like adding it to the config json while would be enough, but I have no idea how to get the required info for it.

![screenshot](https://cloud.githubusercontent.com/assets/3030760/8729467/7322ea7c-2bb9-11e5-9c71-eb3a9e97c353.png)

**Comment by MarcCote** [comment]
To what queue are you referring?

**Comment by samuelstjean** [comment]
qfat3072

**Comment by MarcCote** [comment]
For now, it's reserved and we can't use it. If it gets available someday, we will add it.

**Comment by mgermain** [comment]
Actually, this will be solved by feature #108.
