### ISSUE TITLE
python setup.py install --user

### ISSUE THREAD

**Issue by gyom** [SMART-Lab/smartdispatch#111]
[Disclaimer : This is my first attempt at using smartdispatch and I'm raising this issue here at Mathieu Germain's request.]

I installed smartdispatch on helios through "python setup.py install --user", and I tried a variety of ways to refer to the smartdispatch.py script. I will list here one of those ways. I have no updated by PYTHONPATH because that's not generally required to use the "python setup.py install --user" method.

What I don't understand is that I can load the module fine when I run the python interpreter, but it fails when the same instructions are processed in smartdispatch.py.

Here's a printout from a session.

```
alaingui@helios1 temperature_SPP]$ python /home/alaingui/.local/lib/python2.7/site-packages/smartdispatch/smartdispatch.py --nb_gpus_per_command 1 --walltime=00:01:00:00 launch python ${HOME}/Documents/stormbind/draft/temperature_SPP/script01.py
Traceback (most recent call last):
  File "/home/alaingui/.local/lib/python2.7/site-packages/smartdispatch/smartdispatch.py", line 9, in <module>
    import smartdispatch
  File "/home/alaingui/.local/lib/python2.7/site-packages/smartdispatch/smartdispatch.py", line 10, in <module>
    from smartdispatch import utils
ImportError: cannot import name utils

[alaingui@helios1 temperature_SPP]$ python
Enthought Canopy Python 2.7.6 | 64-bit | (default, Apr 11 2014, 13:46:04) 
[GCC 4.1.2 20080704 (Red Hat 4.1.2-52)] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import smartdispatch
>>> from smartdispatch import utils
>>> 
```

**Comment by MarcCote** [comment]
@gyom I never called the script this way. When you've pip installed it, smart_dispatch.py should be accessible from your PATH via `~/.local/bin/smart_dispatch.py`.

Have you tried either `python ~/.local/bin/smart_dispatch.py -h` or `smart_dispatch.py -h` ?

**Comment by MarcCote** [comment]
@gyom I'm guessing it is working for you? I'll go ahead and close this issue for now.

**Comment by gyom** [comment]
It's working fine for me when I install the thing with pip install. I opened this ticket because Mathieu asked me to do so. I just figured it was a way to track this.

I don't know if the solution is to close this directly, or to add a comment saying that other ways of installing this won't work. I don't know what the typical python user does, but when a library talks about pip install or easy_install, I just assume that I can do whatever I want (including (`python setup.py develop --user`) and the thing will work.

On the flip side, I know that a python library shouldn't be responsible for me putting a pet in the microwave oven and suing the developers because this was not mentioned in the instruction manual.

**Comment by MarcCote** [comment]
Using `pyton setup.py develop --user` or  `pyton setup.py install --user` works for me. 

Something that is confusing is that we have a script called `smart_dispatch.py` (note the underscore) and a module named `smartdispatch.py`. You tried to executed the latter.
