### ISSUE TITLE
Any plans to write docs?

### ISSUE THREAD

**Issue by rizar** [SMART-Lab/smartdispatch#112]
I have just started using smartdispatch and so far I like it. I am curious if you guys have plans to write .rst docs and host them somewhere, e.g. at readthedocs. It would be pretty cool to have docs, for example, the directory structure of SMARTDISPATCH_LOGS folder should be explained somewhere.

**Comment by mgermain** [comment]
Thanks.
We had no short-term plans to do that but we do now. It's true that without doc, the hierarchy of SMARTDISPATCH_LOGS might not be obvious.

**Comment by rizar** [comment]
Great!

Although it did not totally work with Blocks and Fuel, perhaps we can again try to invite people to participate in writing documentation. I would probably contribute once a in while.

**Comment by mgermain** [comment]
Good let's do that!

**Comment by MarcCote** [comment]
I'm closing this one. See #113 instead.
