### ISSUE TITLE
Empty logs should be removed

### ISSUE THREAD

**Issue by MarcCote** [SMART-Lab/smartdispatch#38]
With the workers it would be easy to remove error logs if they are empty. This will reduce the number of small and unused empty log files. The cluster's filesystem will thank us for that ;)

**Comment by mgermain** [comment]
The clusters filesystem would thank us but I'm unsure if we want that behaviour.

Maybe others could chime in.

**Comment by nouiz** [comment]
Unless they cause problem, I would keep them. It is useful to know if the
file was created or not while debugging, even if it is an empty file.

Just my personal opinion, I just read the last comment as offline.

Le jeu. 2 févr. 2017 14:47, Mathieu Germain <notifications@github.com> a
écrit :

**Comment by MarcCote** [comment]
Ok, let's keep them. Anyway, it might change if we ever implement the database approach.
