### ISSUE TITLE
Change the way we handle finished jobs.

### ISSUE THREAD

**Issue by mgermain** [SMART-Lab/smartdispatch#72]
When a worker see that a job is finished but that it returned something different than 0 as exit code (ie: the job has crashed) move it in failed_commands.txt instead of finished_commands.txt.

**Comment by mgermain** [comment]
@MarcCote Do you think reset_running_commands() should put the failed command back in commands.txt or just print a warning or something else ?

**Comment by mgermain** [comment]
Idea for warning :
----------
(#) commands in the past run finished with errors and won't be resumed.
Failed commands:
<command list>
The actual errors can be found in the log folder under:
<list error files>
-----------

**Comment by MarcCote** [comment]
I think what you ended up to do in #80 is fine.
