### ISSUE TITLE
smartdispatch 'launch' command should warn if the same job already exists

### ISSUE THREAD

**Issue by MarcCote** [SMART-Lab/smartdispatch#78]
Running twice smartdispatch with the same command does not warn the user that a job with the same same already exists. When using --pool option, the commands are appended to the previous ones. Without the --pool my guess is that the shell scripts in folder commands will be overwritten.

**Comment by mgermain** [comment]
Now that we pre-pend the date and that we always use --pool under the hood I'm not sure how relevant that is.
This might still be relevant once we start using batchUID but maybe it's just a better idea to always pre-pend the date anyway ?

**Comment by MarcCote** [comment]
Yes, I think we should always prepend the date.
