### ISSUE TITLE
When generating the job folder name, some characters are removed

### ISSUE THREAD

**Issue by MarcCote** [SMART-Lab/smartdispatch#79]
When generating the job folder name, some characters are especially removed to make sure the name does not conflict with how the OS handle its files/folders. However, this means that two jobs' folder name will collide if they only differ by some characters that will be removed even though the jobs produce different commands.

For example, the following commands will generate the same folder name:
`smart_dispatch.py -x -q test -C 1 -t 1:00 -p 2 launch script [-option1\ value1 -option1\ value2]`
`smart_dispatch.py -x -q test -C 1 -t 1:00 -p 2 launch script "[-option1\ value1 -option1\ value2]"`

They produce the same folder name: `script__option1_value1__option1_value2/`
but their commands are different (respectively)
```
script -option1
script value1
script -option1
script value2
```
and
```
script -option1 value1
script -option1 value2
```

**Comment by mgermain** [comment]
The best way to handle that is probably to use UIDs for the batch folders, generated from the escaped string that is after the launch param.

We should also add a file to that folder with the complete original string given to smart_dispatch.

**Comment by MarcCote** [comment]
This means we won't support named batch folders anymore, right? I know @laulysta that you liked having name containing what params/values were used, but as soon as we'll have a basic job viewer I'm sure you'll be fine.

**Comment by mgermain** [comment]
Well if we have a proper viewer it really doesn't matter.
