### ISSUE TITLE
Let smart_worker.py know the #concurrent command and spawn processes accordingly.

### ISSUE THREAD

**Issue by MarcCote** [SMART-Lab/smartdispatch#83]
`smart_worker.py` should be aware of the number of concurrent commands to run on a node. It could then spawn processes accordingly. When a command is finished, and if there is no limit on how many commands it can run, it will spawn another process with another command (if any left).

With this enhancement, PBS file would contain only one command to run: `smart_worker.py ...`.

**Comment by mgermain** [comment]
You mean one worker should handle all the commands on a given node?

**Comment by MarcCote** [comment]
I guess that is what I was trying to say. I don't why, though. :-/

**Comment by mgermain** [comment]
Better control over the resources maybe ?
It's not clear.

**Comment by MarcCote** [comment]
Maybe. But you are right, it's better to close it for now.
