### ISSUE TITLE
Specifiy dependencies

### ISSUE THREAD

**Issue by mgermain** [SMART-Lab/smartdispatch#88]
Mage sure that all the dependencies are in the setpu.py (see http://www.scotttorborg.com/python-packaging/dependencies.html) to ensure a clean installation with pip.

**Comment by MarcCote** [comment]
I think we are already doing that, no?

**Comment by mgermain** [comment]
No, we have at least a dependency on Numpy in `smart_dispatch.py` that is not in the `setup.py` and probably others.

**Comment by mgermain** [comment]
We only had numpy and only for a np.inf so we just removed it in PR #117
